### ISSUE TITLE
creating client certificate after revoking with same entity name

### ISSUE THREAD

**Issue by pqangel** [OpenVPN/easy-rsa#105]
When you revoke access to an entity it creates under ./pki the files:
- index.txt.old
- index.txt.attr.old

if you create another entity with the same name as the one you just revoked access to and try to sign a certificate with:

`./easyrsa sign-req client EntityName`

it will give you an error like this:

```

Certificate is to be certified until Aug 14 18:41:45 2026 GMT (3650 days)
failed to update database
TXT_DB error number 2

Easy-RSA error:

signing failed (openssl output above may have more detail)

```

if you delete this 2 files mentioned above it will allow you to create the certificates without problems.

**Comment by ecrist** [comment]
I've marked this for v3.0.9, but I think it was fixed earlier.  Will confirm.

**Comment by compsup** [comment]
Can this please be fixed? Its really annoying not being able to use a name again.

**Comment by TinCanTech** [comment]
It already *is* fixed. See `easyrsa upgrade ca`

https://community.openvpn.net/openvpn/wiki/easyrsa-upgrade#ersa-up33

**Comment by compsup** [comment]
I am using the easyrsa script found here (https://github.com/angristan/openvpn-install/issues/652). When using this script the issue still persists.

**Comment by TinCanTech** [comment]
Use `easyrsa upgrade ca`

If your version of `easyrsa` does not recognise `upgrade` then upgrade your copy of `easyrsa`.
