### ISSUE TITLE
signing a server fails for unknown reasons (fresh install OpenSUSE Leap, openssl 1.0.2j-13.1)

### ISSUE THREAD

**Issue by BoggGod** [OpenVPN/easy-rsa#168]
While I can sign clients just fine, it somehow complains when I try to do this for server keys. This is using the latest version as of this date, and setting camp with these three simple commands:

```
./easyrsa init-pki
./easyrsa build-ca (with or without nopass)
./easyrsa gen-req server1 (with or without nopass)
```
```
cesar@linux-fmap:~/projects/vpn/easy-rsa/easyrsa3> ./easyrsa sign-req server server1

Note: using Easy-RSA configuration from: ./vars
./easyrsa: line 268: input: command not found


You are about to sign the following certificate.
Please check over the details shown below for accuracy. Note that this request
has not been cryptographically verified. Please be sure it came from a trusted
source or that you have verified the request checksum with the sender.

Request subject, to be signed as a server certificate for 3650 days:

subject=
    commonName                = server1


Type the word 'yes' to continue, or any other input to abort.
  Confirm request details: yes
Using configuration from ./openssl-easyrsa.cnf
ERROR: on line 16 of config file '/home/cesar/projects/vpn/easy-rsa/easyrsa3/pki/extensions.temp'
140088397903504:error:0E079065:configuration file routines:DEF_LOAD_BIO:missing equal sign:conf_def.c:345:line 16

Easy-RSA error:

signing failed (openssl output above may have more detail)

```

**Comment by ecrist** [comment]
Can you pull again?  I think I’ve fixed this…

ecrist@meow:~/easy-rsa/easyrsa3-> ./easyrsa build-ca nopass
Generating a 2048 bit RSA private key
.........+++
..........+++
writing new private key to '/Users/ecrist/easy-rsa/easyrsa3/pki/private/ca.key.N4tPQL12Dl'
-----
You are about to be asked to enter information that will be incorporated
into your certificate request.
What you are about to enter is what is called a Distinguished Name or a DN.
There are quite a few fields but you can leave some blank
For some fields there will be a default value,
If you enter '.', the field will be left blank.
-----
Common Name (eg: your user, host, or server name) [Easy-RSA CA]:

CA creation complete and you may now import and sign cert requests.
Your new CA certificate file for publishing is at:
/Users/ecrist/easy-rsa/easyrsa3/pki/ca.crt

ecrist@meow:~/easy-rsa/easyrsa3-> ./easyrsa gen-req server1 nopass
Generating a 2048 bit RSA private key
.................................................+++
.....+++
writing new private key to '/Users/ecrist/easy-rsa/easyrsa3/pki/private/server1.key.1rNRQpQCnh'
-----
You are about to be asked to enter information that will be incorporated
into your certificate request.
What you are about to enter is what is called a Distinguished Name or a DN.
There are quite a few fields but you can leave some blank
For some fields there will be a default value,
If you enter '.', the field will be left blank.
-----
Common Name (eg: your user, host, or server name) [server1]:

Keypair and certificate request completed. Your files are:
req: /Users/ecrist/easy-rsa/easyrsa3/pki/reqs/server1.req
key: /Users/ecrist/easy-rsa/easyrsa3/pki/private/server1.key

**Comment by BoggGod** [comment]
I'm a bit confused. In your pasted code, you are not actually signing the generated key with the certificate authority, which is where I experience problems.

I've pulled again, but with the same result:

```
cesar@linux-fmap:~/projects/vpn/easy-rsa/easyrsa3> ./easyrsa init-pki

Note: using Easy-RSA configuration from: ./vars

init-pki complete; you may now create a CA or requests.
Your newly created PKI dir is: /home/cesar/projects/vpn/easy-rsa/easyrsa3/pki

cesar@linux-fmap:~/projects/vpn/easy-rsa/easyrsa3> ./easyrsa build-ca nopass

Note: using Easy-RSA configuration from: ./vars
Generating a 2048 bit RSA private key
..............................+++
........................................................................................................................................................................................................+++
writing new private key to '/home/cesar/projects/vpn/easy-rsa/easyrsa3/pki/private/ca.key.bIOY4D890g'
-----
You are about to be asked to enter information that will be incorporated
into your certificate request.
What you are about to enter is what is called a Distinguished Name or a DN.
There are quite a few fields but you can leave some blank
For some fields there will be a default value,
If you enter '.', the field will be left blank.
-----
Common Name (eg: your user, host, or server name) [Easy-RSA CA]:

CA creation complete and you may now import and sign cert requests.
Your new CA certificate file for publishing is at:
/home/cesar/projects/vpn/easy-rsa/easyrsa3/pki/ca.crt

cesar@linux-fmap:~/projects/vpn/easy-rsa/easyrsa3> ./easyrsa gen-req server1 nopass

Note: using Easy-RSA configuration from: ./vars
Generating a 2048 bit RSA private key
............................+++
..............................+++
writing new private key to '/home/cesar/projects/vpn/easy-rsa/easyrsa3/pki/private/server1.key.waXGTJ9rTn'
-----
You are about to be asked to enter information that will be incorporated
into your certificate request.
What you are about to enter is what is called a Distinguished Name or a DN.
There are quite a few fields but you can leave some blank
For some fields there will be a default value,
If you enter '.', the field will be left blank.
-----
Common Name (eg: your user, host, or server name) [server1]:

Keypair and certificate request completed. Your files are:
req: /home/cesar/projects/vpn/easy-rsa/easyrsa3/pki/reqs/server1.req
key: /home/cesar/projects/vpn/easy-rsa/easyrsa3/pki/private/server1.key

cesar@linux-fmap:~/projects/vpn/easy-rsa/easyrsa3> ./easyrsa sign-req server server1

Note: using Easy-RSA configuration from: ./vars


You are about to sign the following certificate.
Please check over the details shown below for accuracy. Note that this request
has not been cryptographically verified. Please be sure it came from a trusted
source or that you have verified the request checksum with the sender.

Request subject, to be signed as a server certificate for 3650 days:

subject=
    commonName                = server1


Type the word 'yes' to continue, or any other input to abort.
  Confirm request details: yes
Using configuration from ./openssl-easyrsa.cnf
ERROR: on line 16 of config file '/home/cesar/projects/vpn/easy-rsa/easyrsa3/pki/extensions.temp'
140627610957456:error:02001002:system library:fopen:No such file or directory:bss_file.c:179:fopen('/home/cesarrojects/vpn/easy-rsa/easyrsa3/pki/index.txt.attr','rb')
140627610957456:error:2006D080:BIO routines:BIO_new_file:no such file:bss_file.c:186:
140627610957456:error:0E078072:configuration file routines:DEF_LOAD:no such file:conf_def.c:195:
140627610957456:error:0E079065:configuration file routines:DEF_LOAD_BIO:missing equal sign:conf_def.c:345:line 

Easy-RSA error:

signing failed (openssl output above may have more detail)
```

**Comment by BoggGod** [comment]
Ok, as someone kindly pointed out to me in the IRC, commenting out lines 655-659 in the executable 'easyrsa' allows the signing of servers. The real problem is that I thought this was the stable branch. Sorry, and thanks :)

**Comment by petersm1** [comment]
Still getting these error, should this issue been fixed ?

`23370702888576:error:02001002:system library:fopen:No such file or directory:bss_file.c:175:fopen('/mnt/cache/appdata/myVPN_2/easy-rsa/easyrsa3/pki/index.txt.attr','rb')
23370702888576:error:2006D080:BIO routines:BIO_new_file:no such file:bss_file.c:182:
23370702888576:error:0E078072:configuration file routines:DEF_LOAD:no such file:conf_def.c:201:
23370702888576:error:0E079065:configuration file routines:DEF_LOAD_BIO:missing equal sign:conf_def.c:351:line 16

Easy-RSA error:

signing failed (openssl output above may have more detail)`

**Comment by ecrist** [comment]
Did you run initpki first?

Eric Crist

**Comment by ecrist** [comment]
I think this is fixed in b3ed480.

**Comment by petersm1** [comment]
When can we see this update in the master ?

Thanks for the bug fix!

**Comment by kaspergrubbe** [comment]
@petersm1 Not sure if you noticed, but this went live with the release of 3.0.4.

**Comment by JakobSch** [comment]
I am quite sorry to inform you, but the bug seems to be still present in tag v3.0.4 and current master.
My 'git contains' tells me, that the commit is in tag 'v3.0.4', however one line looks like it got changed back between the fix and 'v3.0.4'.
I am at v3.0.4 and changing the following fixed the issue for me: (note, that this is a change allready included in the fix from this thread)
```
        echo "$EASYRSA_EXTRA_EXTS" | 
          grep -q subjectAltName || 
-         default_server_san $req_in
+         print "subjectAltName = DNS:$sname"
      fi
```
(I modified the whitespace for the code display)

Am I mistaken somewhere?
greetz,
Jakke

**Comment by ecrist** [comment]
This isn’t a complete fix, as it doesn’t account for an IP address, and there may be other corner cases.

Eric

**Comment by JakobSch** [comment]
Hey, thanks for the quick reply. I believe you as I have no clue how the code works, however this issue here should not be closed then, right?

**Comment by saikriss** [comment]
Hi all,
I also have similar issue.
When CA try to import **server.req**  for  giving certificate, i got this error:
**Easy-RSA error:

The input file does not appear to be a certificate request. Aborting import.
Offending file: /tmp/server1.req**

Can someone help me.
I am running it on ubuntu 18.04 and openvpn version (2.4.4-2ubuntu1.1)
thanks

**Comment by saikriss** [comment]
Hi all,

I have solved the error. Actually when we are dealing with certifying a client or server request, we have to give root permission to do the operations. Like the command "./easyrsa import-req /tmp/client2.key client" should be done in root or using sudo. 
Thanks

> Hi all,
> I also have similar issue.
> When CA try to import **server.req** for giving certificate, i got this error:
> **Easy-RSA error:
> 
> The input file does not appear to be a certificate request. Aborting import.
> Offending file: /tmp/server1.req**
> 
> Can someone help me.
> I am running it on ubuntu 18.04 and openvpn version (2.4.4-2ubuntu1.1)
> thanks

**Comment by TinCanTech** [comment]
> we have to give root permission to do the operations

Because you are trying to write to a protected system area.
The first comment in `vars.example` is:

```
# NOTE: If you installed Easy-RSA from your distro's package manager, don't edit
# this file in place -- instead, you should copy the entire easy-rsa directory
# to another location so future upgrades don't wipe out your changes.
```

**Comment by saikriss** [comment]
yes @TinCanTech,  you are right. Due to time constraint, i overlooked these files. 
Thanks
