### ISSUE TITLE
quoted ampersand in `vars` leads to unexpected behaviour

### ISSUE THREAD

**Issue by tobwen** [OpenVPN/easy-rsa#364]
The name of our corporation contains an ampersand, which was entered in `vars` like this:
```
set_var EASYRSA_REQ_ORG         "Science & Knowledge"
```

This lead to strange results when running `./easyrsa build-ca`:
```
Using SSL: openssl OpenSSL 1.1.1d  10 Sep 2019
Generating RSA private key, 2048 bit long modulus (2 primes)
.........+++++
...........................................................................................+++++
e is 65537 (0x010001)
req: Error on line 90 of config file "/root/EasyRSA-v3.0.6/pki/safessl-easyrsa.cnf"
req: Error on line 90 of config file "/root/EasyRSA-v3.0.6/pki/safessl-easyrsa.cnf"
unable to find 'distinguished_name' in config
problems making Certificate Request
140097663571072:error:0E06D06A:configuration file routines:NCONF_get_string:no conf or environment variable:../crypto/conf/conf_lib.c:270:

Easy-RSA error:

Failed to build the CA
```

This, of course made no sense. Change the ampersand to *and* or escaping it, made the process work:
```
set_var EASYRSA_REQ_ORG         "Science and Knowledge"
set_var EASYRSA_REQ_ORG         "Science \& Knowledge"
```

**Comment by ecrist** [comment]
What version of EasyRSA?  I think this was fixed a while ago. 

Eric Crist

**Comment by tobwen** [comment]
EasyRSA v3.0.6 (current release version)

**Comment by TinCanTech** [comment]
The Windows version of `easyrsa` does not allow ampersand, escaped or not. So '&' is considered to be an unsupportable character in `easyrsa`. (at this time)

**Comment by ecrist** [comment]
It appears this is also an issue with LibreSSL.  I'm going to push this out to 3.1 for now as a punt.

**Comment by dorianfm** [comment]
I can confirm this issue still exists in Easy RSA v3.0.8 with OpenSSL

Having mirated my configuration from Easy RSA 2 to v3.0.8 using

```
easyrsa upgrade pki
```
I started encountering this error.

example output:

```
:/etc/openvpn/easyrsa3# ./easyrsa build-client-full [redacted]

Note: using Easy-RSA configuration from: /etc/openvpn/easyrsa3/vars
Using SSL: openssl OpenSSL 1.1.1f  31 Mar 2020
req: Error on line 91 of config file "/etc/openvpn/easyrsa3/pki/easy-rsa-1261574.86LqLF/tmp.HBgF8c"
139750548825408:error:0E065068:configuration file routines:str_copy:variable has no value:../crypto/conf/conf_def.c:622:line 91

Easy-RSA error:

Failed to generate request
```

or

```
:/etc/openvpn/easyrsa3# ./easyrsa update-db

Note: using Easy-RSA configuration from: /etc/openvpn/easyrsa3/vars
Using SSL: openssl OpenSSL 1.1.1f  31 Mar 2020
Using configuration from /etc/openvpn/easyrsa3/pki/easy-rsa-1288436.zd03HI/tmp.DrUMp1
ca: Error on line 91 of config file "/etc/openvpn/easyrsa3/pki/easy-rsa-1288436.zd03HI/tmp.DrUMp1"
139917168825664:error:0E065068:configuration file routines:str_copy:variable has no value:../crypto/conf/conf_def.c:622:line 91
```

Looking at ```./pki/openssl-easyrsa.cnf``` line 91:

```
organizationalUnitName_default  = $ENV::EASYRSA_REQ_OU
```

then looking in vars I had
```
set_var EASYRSA_REQ_OU "Department of Security & Encryption"
```

Removing the & in ```./vars``` fixed the issue and has allowed me to ```update-db``` and ```build-client-full``` without issue

**Comment by TinCanTech** [comment]
FTR: No matter how you try to use `&`, it does **not** work in Windows.

**Comment by baquilla** [comment]
The ampersand character is special for sed. Translations to generate safe config file (makesafeconf) for LibreSSL, which is indeed not required for OpenSSL, are messing things. 

For those who are using OpenSSL and need to go ahead just replace the variable to use the original config.

```
--- a/easyrsa3/easyrsa
+++ b/easyrsa3/easyrsa
@@ -404,7 +404,7 @@ easyrsa_openssl() {
                cp "$easyrsa_openssl_conf" "$EASYRSA_SAFE_CONF"
                err=$?
        else
-               "$EASYRSA_OPENSSL" "$openssl_command" -config "$easyrsa_openssl_conf" "$@"
+               "$EASYRSA_OPENSSL" "$openssl_command" -config "$EASYRSA_SSL_CONF" "$@"
                err=$?
        fi
```

For a complete solution "&" must be escaped this way ${EASYRSA_PKI//&/\\&} or any other. That's supported in Bash but may not be available in other shells.

```
--- a/easyrsa3/easyrsa
+++ b/easyrsa3/easyrsa
@@ -381,21 +381,21 @@ easyrsa_openssl() {
        # Make LibreSSL safe config file from OpenSSL config file
        sed \
                -e "s\`ENV::EASYRSA\`EASYRSA\`g" \
-               -e "s\`\$dir\`$EASYRSA_PKI\`g" \
-               -e "s\`\$EASYRSA_PKI\`$EASYRSA_PKI\`g" \
+               -e "s\`\$dir\`${EASYRSA_PKI//&/\\&}\`g" \
+               -e "s\`\$EASYRSA_PKI\`${EASYRSA_PKI//&/\\&}\`g" \
                -e "s\`\$EASYRSA_CERT_EXPIRE\`$EASYRSA_CERT_EXPIRE\`g" \
                -e "s\`\$EASYRSA_CRL_DAYS\`$EASYRSA_CRL_DAYS\`g" \
                -e "s\`\$EASYRSA_DIGEST\`$EASYRSA_DIGEST\`g" \
                -e "s\`\$EASYRSA_KEY_SIZE\`$EASYRSA_KEY_SIZE\`g" \
                -e "s\`\$EASYRSA_DIGEST\`$EASYRSA_DIGEST\`g" \
-               -e "s\`\$EASYRSA_DN\`$EASYRSA_DN\`g" \
-               -e "s\`\$EASYRSA_REQ_COUNTRY\`$EASYRSA_REQ_COUNTRY\`g" \
-               -e "s\`\$EASYRSA_REQ_PROVINCE\`$EASYRSA_REQ_PROVINCE\`g" \
-               -e "s\`\$EASYRSA_REQ_CITY\`$EASYRSA_REQ_CITY\`g" \
-               -e "s\`\$EASYRSA_REQ_ORG\`$EASYRSA_REQ_ORG\`g" \
-               -e "s\`\$EASYRSA_REQ_OU\`$EASYRSA_REQ_OU\`g" \
-               -e "s\`\$EASYRSA_REQ_CN\`$EASYRSA_REQ_CN\`g" \
-               -e "s\`\$EASYRSA_REQ_EMAIL\`$EASYRSA_REQ_EMAIL\`g" \
+               -e "s\`\$EASYRSA_DN\`${EASYRSA_DN}\`g" \
+               -e "s\`\$EASYRSA_REQ_COUNTRY\`${EASYRSA_REQ_COUNTRY//&/\\&}\`g" \
+               -e "s\`\$EASYRSA_REQ_PROVINCE\`${EASYRSA_REQ_PROVINCE//&/\\&}\`g" \
+               -e "s\`\$EASYRSA_REQ_CITY\`${EASYRSA_REQ_CITY//&/\\&}\`g" \
+               -e "s\`\$EASYRSA_REQ_ORG\`${EASYRSA_REQ_ORG//&/\\&}\`g" \
+               -e "s\`\$EASYRSA_REQ_OU\`${EASYRSA_REQ_OU//&/\\&}\`g" \
+               -e "s\`\$EASYRSA_REQ_CN\`${EASYRSA_REQ_CN//&/\\&}\`g" \
+               -e "s\`\$EASYRSA_REQ_EMAIL\`${EASYRSA_REQ_EMAIL//&/\\&}\`g" \
                ${EASYRSA_EXTRA_EXTS:+-e "/^#%EXTRA_EXTS%/r $easyrsa_extra_exts"} \
                "$EASYRSA_SSL_CONF" > "$easyrsa_openssl_conf" ||
                die "Failed to update $easyrsa_openssl_conf"
```

I currently have no time for testing and PR it but wanted to share my insights.

**Comment by TinCanTech** [comment]
Neither of these apply to master and you have not included your version.

**Comment by TinCanTech** [comment]
`easyrsa3-master-ampersand.diff`
```
diff --git a/easyrsa3/easyrsa b/easyrsa3/easyrsa
index 9c7153b..d51b16e 100755
--- a/easyrsa3/easyrsa
+++ b/easyrsa3/easyrsa
@@ -378,24 +378,37 @@ easyrsa_openssl() {
 		EOF
 	fi
 
+
+		#-e "s\`ENV::EASYRSA\`EASYRSA\`g" \
+		#-e "s\`\$dir\`$EASYRSA_PKI\`g" \
+
+		#-e "s\`\$EASYRSA_DN\`$EASYRSA_DN\`g" \
+		#-e "s\`\$EASYRSA_REQ_COUNTRY\`$EASYRSA_REQ_COUNTRY\`g" \
+		#-e "s\`\$EASYRSA_REQ_PROVINCE\`$EASYRSA_REQ_PROVINCE\`g" \
+		#-e "s\`\$EASYRSA_REQ_CITY\`$EASYRSA_REQ_CITY\`g" \
+		#-e "s\`\$EASYRSA_REQ_ORG\`$EASYRSA_REQ_ORG\`g" \
+		#-e "s\`\$EASYRSA_REQ_OU\`$EASYRSA_REQ_OU\`g" \
+		#-e "s\`\$EASYRSA_REQ_CN\`$EASYRSA_REQ_CN\`g" \
+		#-e "s\`\$EASYRSA_REQ_EMAIL\`$EASYRSA_REQ_EMAIL\`g" \
+
 	# Make LibreSSL safe config file from OpenSSL config file
 	sed \
-		-e "s\`ENV::EASYRSA\`EASYRSA\`g" \
-		-e "s\`\$dir\`$EASYRSA_PKI\`g" \
+			-e "s\`\$dir\`${EASYRSA_PKI//&/\\&}\`g" \
+			-e "s\`\$EASYRSA_PKI\`${EASYRSA_PKI//&/\\&}\`g" \
 		-e "s\`\$EASYRSA_PKI\`$EASYRSA_PKI\`g" \
 		-e "s\`\$EASYRSA_CERT_EXPIRE\`$EASYRSA_CERT_EXPIRE\`g" \
 		-e "s\`\$EASYRSA_CRL_DAYS\`$EASYRSA_CRL_DAYS\`g" \
 		-e "s\`\$EASYRSA_DIGEST\`$EASYRSA_DIGEST\`g" \
 		-e "s\`\$EASYRSA_KEY_SIZE\`$EASYRSA_KEY_SIZE\`g" \
 		-e "s\`\$EASYRSA_DIGEST\`$EASYRSA_DIGEST\`g" \
-		-e "s\`\$EASYRSA_DN\`$EASYRSA_DN\`g" \
-		-e "s\`\$EASYRSA_REQ_COUNTRY\`$EASYRSA_REQ_COUNTRY\`g" \
-		-e "s\`\$EASYRSA_REQ_PROVINCE\`$EASYRSA_REQ_PROVINCE\`g" \
-		-e "s\`\$EASYRSA_REQ_CITY\`$EASYRSA_REQ_CITY\`g" \
-		-e "s\`\$EASYRSA_REQ_ORG\`$EASYRSA_REQ_ORG\`g" \
-		-e "s\`\$EASYRSA_REQ_OU\`$EASYRSA_REQ_OU\`g" \
-		-e "s\`\$EASYRSA_REQ_CN\`$EASYRSA_REQ_CN\`g" \
-		-e "s\`\$EASYRSA_REQ_EMAIL\`$EASYRSA_REQ_EMAIL\`g" \
+			-e "s\`\$EASYRSA_DN\`${EASYRSA_DN}\`g" \
+			-e "s\`\$EASYRSA_REQ_COUNTRY\`${EASYRSA_REQ_COUNTRY//&/\\&}\`g" \
+			-e "s\`\$EASYRSA_REQ_PROVINCE\`${EASYRSA_REQ_PROVINCE//&/\\&}\`g" \
+			-e "s\`\$EASYRSA_REQ_CITY\`${EASYRSA_REQ_CITY//&/\\&}\`g" \
+			-e "s\`\$EASYRSA_REQ_ORG\`${EASYRSA_REQ_ORG//&/\\&}\`g" \
+			-e "s\`\$EASYRSA_REQ_OU\`${EASYRSA_REQ_OU//&/\\&}\`g" \
+			-e "s\`\$EASYRSA_REQ_CN\`${EASYRSA_REQ_CN//&/\\&}\`g" \
+			-e "s\`\$EASYRSA_REQ_EMAIL\`${EASYRSA_REQ_EMAIL//&/\\&}\`g" \
 		${EASYRSA_EXTRA_EXTS:+-e "/^#%EXTRA_EXTS%/r $easyrsa_extra_exts"} \
 		"$EASYRSA_SSL_CONF" > "$easyrsa_openssl_conf" ||
 		die "Failed to update $easyrsa_openssl_conf"
@@ -404,7 +417,8 @@ easyrsa_openssl() {
 		cp "$easyrsa_openssl_conf" "$EASYRSA_SAFE_CONF"
 		err=$?
 	else
-		"$EASYRSA_OPENSSL" "$openssl_command" -config "$easyrsa_openssl_conf" "$@"
+#		"$EASYRSA_OPENSSL" "$openssl_command" -config "$easyrsa_openssl_conf" "$@"
+		"$EASYRSA_OPENSSL" "$openssl_command" -config "$EASYRSA_SSL_CONF" "$@"
 		err=$?
 	fi
 
```

**Comment by baquilla** [comment]
Sorry, that was not pretending to be a patch, I just wanted to share my tests and help following up instead of fixing only for myself. I took a bit more time to review. It was running just with Bash. Bellow patch also works with Dash, it looks more portable.

`easyrsa3-master-ampersand.diff` Barely tested with Bash and Dash.

```
diff --git a/easyrsa3/easyrsa b/easyrsa3/easyrsa
index 36e154d..763d2b2 100755
--- a/easyrsa3/easyrsa
+++ b/easyrsa3/easyrsa
@@ -379,23 +379,24 @@ easyrsa_openssl() {
        fi

        # Make LibreSSL safe config file from OpenSSL config file
+       _sed_sanitize() { printf "%s" "$*" | sed 's/[&/\]/\\&/g'; }
        sed \
                -e "s\`ENV::EASYRSA\`EASYRSA\`g" \
-               -e "s\`\$dir\`$EASYRSA_PKI\`g" \
-               -e "s\`\$EASYRSA_PKI\`$EASYRSA_PKI\`g" \
+               -e "s\`\$dir\`$(_sed_sanitize "${EASYRSA_PKI}")\`g" \
+               -e "s\`\$EASYRSA_PKI\`$(_sed_sanitize "$EASYRSA_PKI")\`g" \
                -e "s\`\$EASYRSA_CERT_EXPIRE\`$EASYRSA_CERT_EXPIRE\`g" \
                -e "s\`\$EASYRSA_CRL_DAYS\`$EASYRSA_CRL_DAYS\`g" \
                -e "s\`\$EASYRSA_DIGEST\`$EASYRSA_DIGEST\`g" \
                -e "s\`\$EASYRSA_KEY_SIZE\`$EASYRSA_KEY_SIZE\`g" \
                -e "s\`\$EASYRSA_DIGEST\`$EASYRSA_DIGEST\`g" \
-               -e "s\`\$EASYRSA_DN\`$EASYRSA_DN\`g" \
-               -e "s\`\$EASYRSA_REQ_COUNTRY\`$EASYRSA_REQ_COUNTRY\`g" \
-               -e "s\`\$EASYRSA_REQ_PROVINCE\`$EASYRSA_REQ_PROVINCE\`g" \
-               -e "s\`\$EASYRSA_REQ_CITY\`$EASYRSA_REQ_CITY\`g" \
-               -e "s\`\$EASYRSA_REQ_ORG\`$EASYRSA_REQ_ORG\`g" \
-               -e "s\`\$EASYRSA_REQ_OU\`$EASYRSA_REQ_OU\`g" \
-               -e "s\`\$EASYRSA_REQ_CN\`$EASYRSA_REQ_CN\`g" \
-               -e "s\`\$EASYRSA_REQ_EMAIL\`$EASYRSA_REQ_EMAIL\`g" \
+               -e "s\`\$EASYRSA_DN\`$(_sed_sanitize "$EASYRSA_DN")\`g" \
+               -e "s\`\$EASYRSA_REQ_COUNTRY\`$(_sed_sanitize "$EASYRSA_REQ_COUNTRY")\`g" \
+               -e "s\`\$EASYRSA_REQ_PROVINCE\`$(_sed_sanitize "$EASYRSA_REQ_PROVINCE")\`g" \
+               -e "s\`\$EASYRSA_REQ_CITY\`$(_sed_sanitize "$EASYRSA_REQ_CITY")\`g" \
+               -e "s\`\$EASYRSA_REQ_ORG\`$(_sed_sanitize "$EASYRSA_REQ_ORG")\`g" \
+               -e "s\`\$EASYRSA_REQ_OU\`$(_sed_sanitize "$EASYRSA_REQ_OU")\`g" \
+               -e "s\`\$EASYRSA_REQ_CN\`$(_sed_sanitize "$EASYRSA_REQ_CN")\`g" \
+               -e "s\`\$EASYRSA_REQ_EMAIL\`$(_sed_sanitize "$EASYRSA_REQ_EMAIL")\`g" \
                ${EASYRSA_EXTRA_EXTS:+-e "/^#%EXTRA_EXTS%/r $easyrsa_extra_exts"} \
                "$EASYRSA_SSL_CONF" > "$easyrsa_openssl_conf" ||
                die "Failed to update $easyrsa_openssl_conf"
```

**Comment by TinCanTech** [comment]
I'll test it soon. Thanks.

**Comment by TinCanTech** [comment]
This is the result:
```
tct@home:~/git/tct/easy-rsa/master/easyrsa3$ ./easyrsa init-pki

Note: using Easy-RSA configuration from: /home/tct/git/tct/easy-rsa/master/easyrsa3/vars
./easyrsa: 395: Bad substitution

```

**Comment by TinCanTech** [comment]
`shellcheck` analysis:
```
In easyrsa line 396:
			-e "s\`\$dir\`${EASYRSA_PKI//&/\\&}\`g" \
                                      ^-------------------^ SC2039: In POSIX sh, string replacement is undefined.
```

**Comment by TinCanTech** [comment]
The fix will probably break `vars` files with escaped `&`.  However, in order to have a working `vars` file with an escaped `&` means that you are using a customised `easyrsa` ...
